baseURL: 'https://mirkoschubert.com/'
languageCode: en-us
title: Mirko Schubert
theme: after-dark
related_content_limit: 5
disableKinds:
  - taxonomy
  - taxonomyTerm
ignoreFiles:
  - "static/assets/sass/*"
blackfriday:
  hrefTargetBlank: true
  fractions: false
