DefaultContentLanguage: en
languages:
  en:
    baseURL: 'https://mirkoschubert.com'
    contentDir: content.en
    languageName: English
    languageCode: en-us
    title: Mirko Schubert
    slogan: Journalist ∙ Musician ∙ Developer
    weight: 1
  de:
    baseUrl: 'https://mirkoschubert.de'
    contentDir: content.de
    languageName: Deutsch
    languageCode: de-de
    title: Mirko Schubert
    slogan: Journalist ∙ Musiker ∙ Entwickler
    permalinks:
      articles: '/artikel/:title'
    weight: 2
theme: oldterm
related_content_limit: 5
disableKinds:
  - taxonomy
  - taxonomyTerm
blackfriday:
  hrefTargetBlank: true
  fractions: false