baseURL = "https://mirkoschubert.com/"
languageCode = "en-us"
title = "Mirko Schubert"
theme = "after-dark"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/posts/"

related_content_limit = 5

[blackfriday]
hrefTargetBlank = true
fractions = false